# Generated by Django 6.1.1 on 2026-09-18 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('small_blind', models.DecimalField(decimal_places=2, max_digits=6)),
                ('big_blind', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_seats', models.IntegerField(default=6)),
                ('community_cards', models.CharField(blank=True, db_default='', max_length=20)),
                ('pot', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_game_running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SlotMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_bet', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('max_bet', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('rtp', models.FloatField(default=96.5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('game_type', models.CharField(choices=[('POKER', 'Покер'), ('SLOTS', 'Слоти'), ('SYSTEM', 'Каса(Поповнення/Виведення )')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='poker.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SlotSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('win_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('combination', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_spin', to='poker.slotmachine')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_spin', to='poker.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PokerSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('chips_in_game', models.DecimalField(decimal_places=2, max_digits=10)),
                ('player_cards', models.CharField(blank=True, default='', max_length=10)),
                ('is_folded', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='poker.playerprofile')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='poker.pokertable')),
            ],
            options={
                'unique_together': {('table', 'seat_number')},
            },
        ),
    ]
